### ISSUE TITLE
aii-dhcp plugin/module usage

### ISSUE THREAD

**Issue by stdweird** [quattor/aii#184] opened 2016-07-01 07:28 UTC
is anyone using the `NCM::Component::dhcp` plug-in/module in https://github.com/quattor/aii/tree/master/aii-dhcp/src/main/perl?

I would like to make some changes to the `aii-dhcp` script, which does not seem to use it at all, and find it confusing that the module also exists.

If no-one uses it, i propose to remove it. if it is being used, I might look at refactoring the code in aii-dhcp script and the plug-in.

**Comment by stdweird** [comment] 2016-07-01 07:28
@gombasg you seem to have made the initial commit. is it in use at MS?

**Comment by kwaegema** [comment] 2017-02-27 12:24
This looks like #166. Right now aii-shellfe uses aii-core/DHCP module, which is also used by aii-dhcp. So I would not know where the plugin/module would be used. So unless somebody uses this in his own fork, it is probably better deleted, since it has almost the same code as aii-core/DHCP, except for the interface

**Comment by jrha** [comment] 2017-03-21 16:08
Duplicate of #166.

**Closed by jrha** 2017-03-21 16:08 UTC
Labels: discuss at workshop
